#############################################################################
# Makefile for building: cuACS
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  cuACS.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cuACS.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cuACS1.0.0
DISTDIR = /media/sf_git/viewMatch/COMP_3004/.tmp/cuACS1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Control.cpp \
		Animal.cpp \
		AnimalTableModel.cpp \
		ManageAnimalsView.cpp \
		AddAnimalDialog.cpp \
		Store.cpp \
		ClientTableModel.cpp \
		Client.cpp \
		DBHandler.cpp \
		ManageClientsView.cpp \
		Login.cpp \
		CuacsAppView.cpp \
		ClientManageStore.cpp \
		BrowseAnimals.cpp \
		Staff.cpp \
		StaffCollection.cpp \
		AddClientDialog.cpp \
		SidebarClient.cpp \
		SidebarStaff.cpp \
		StaffManageStore.cpp \
		Default.cpp \
		DBQuery.cpp \
		AnimalCollection.cpp \
		ClientCollection.cpp \
		StoreControl.cpp \
		EditAnimalDialog.cpp \
		LoginControl.cpp \
		EditClientDialog.cpp \
		ManageMatchesView.cpp \
		MatchTableModel.cpp \
		MatchingAlgorithm.cpp \
		KuhnMunkres.cpp qrc_stylesheet.cpp \
		moc_AnimalTableModel.cpp \
		moc_ManageAnimalsView.cpp \
		moc_AddAnimalDialog.cpp \
		moc_Store.cpp \
		moc_ClientTableModel.cpp \
		moc_ManageClientsView.cpp \
		moc_Login.cpp \
		moc_CuacsAppView.cpp \
		moc_ClientManageStore.cpp \
		moc_BrowseAnimals.cpp \
		moc_StaffCollection.cpp \
		moc_AddClientDialog.cpp \
		moc_SidebarClient.cpp \
		moc_SidebarStaff.cpp \
		moc_StaffManageStore.cpp \
		moc_Default.cpp \
		moc_EditAnimalDialog.cpp \
		moc_EditClientDialog.cpp \
		moc_ManageMatchesView.cpp \
		moc_MatchTableModel.cpp
OBJECTS       = main.o \
		Control.o \
		Animal.o \
		AnimalTableModel.o \
		ManageAnimalsView.o \
		AddAnimalDialog.o \
		Store.o \
		ClientTableModel.o \
		Client.o \
		DBHandler.o \
		ManageClientsView.o \
		Login.o \
		CuacsAppView.o \
		ClientManageStore.o \
		BrowseAnimals.o \
		Staff.o \
		StaffCollection.o \
		AddClientDialog.o \
		SidebarClient.o \
		SidebarStaff.o \
		StaffManageStore.o \
		Default.o \
		DBQuery.o \
		AnimalCollection.o \
		ClientCollection.o \
		StoreControl.o \
		EditAnimalDialog.o \
		LoginControl.o \
		EditClientDialog.o \
		ManageMatchesView.o \
		MatchTableModel.o \
		MatchingAlgorithm.o \
		KuhnMunkres.o \
		qrc_stylesheet.o \
		moc_AnimalTableModel.o \
		moc_ManageAnimalsView.o \
		moc_AddAnimalDialog.o \
		moc_Store.o \
		moc_ClientTableModel.o \
		moc_ManageClientsView.o \
		moc_Login.o \
		moc_CuacsAppView.o \
		moc_ClientManageStore.o \
		moc_BrowseAnimals.o \
		moc_StaffCollection.o \
		moc_AddClientDialog.o \
		moc_SidebarClient.o \
		moc_SidebarStaff.o \
		moc_StaffManageStore.o \
		moc_Default.o \
		moc_EditAnimalDialog.o \
		moc_EditClientDialog.o \
		moc_ManageMatchesView.o \
		moc_MatchTableModel.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro Control.h \
		Animal.h \
		AnimalTableModel.h \
		ManageAnimalsView.h \
		AddAnimalDialog.h \
		Store.h \
		ClientTableModel.h \
		Client.h \
		DBHandler.h \
		ManageClientsView.h \
		Login.h \
		CuacsAppView.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		Staff.h \
		StaffCollection.h \
		AddClientDialog.h \
		SidebarClient.h \
		SidebarStaff.h \
		StaffManageStore.h \
		Default.h \
		DBQuery.h \
		AnimalCollection.h \
		ClientCollection.h \
		StoreControl.h \
		EditAnimalDialog.h \
		LoginControl.h \
		EditClientDialog.h \
		Constants.h \
		ManageMatchesView.h \
		MatchTableModel.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h main.cpp \
		Control.cpp \
		Animal.cpp \
		AnimalTableModel.cpp \
		ManageAnimalsView.cpp \
		AddAnimalDialog.cpp \
		Store.cpp \
		ClientTableModel.cpp \
		Client.cpp \
		DBHandler.cpp \
		ManageClientsView.cpp \
		Login.cpp \
		CuacsAppView.cpp \
		ClientManageStore.cpp \
		BrowseAnimals.cpp \
		Staff.cpp \
		StaffCollection.cpp \
		AddClientDialog.cpp \
		SidebarClient.cpp \
		SidebarStaff.cpp \
		StaffManageStore.cpp \
		Default.cpp \
		DBQuery.cpp \
		AnimalCollection.cpp \
		ClientCollection.cpp \
		StoreControl.cpp \
		EditAnimalDialog.cpp \
		LoginControl.cpp \
		EditClientDialog.cpp \
		ManageMatchesView.cpp \
		MatchTableModel.cpp \
		MatchingAlgorithm.cpp \
		KuhnMunkres.cpp
QMAKE_TARGET  = cuACS
DESTDIR       = 
TARGET        = cuACS


first: all
####### Build rules

$(TARGET): ui_ManageAnimalsView.h ui_AddAnimalDialog.h ui_ManageClientsView.h ui_Login.h ui_CuacsAppView.h ui_ClientManageStore.h ui_BrowseAnimals.h ui_AddClientDialog.h ui_SidebarClient.h ui_SidebarStaff.h ui_StaffManageStore.h ui_Default.h ui_EditAnimalDialog.h ui_EditClientDialog.h ui_ManageMatchesView.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cuACS.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro \
		stylesheet.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile cuACS.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cuACS.pro:
stylesheet.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cuACS.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents stylesheet.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Control.h Animal.h AnimalTableModel.h ManageAnimalsView.h AddAnimalDialog.h Store.h ClientTableModel.h Client.h DBHandler.h ManageClientsView.h Login.h CuacsAppView.h ClientManageStore.h BrowseAnimals.h Staff.h StaffCollection.h AddClientDialog.h SidebarClient.h SidebarStaff.h StaffManageStore.h Default.h DBQuery.h AnimalCollection.h ClientCollection.h StoreControl.h EditAnimalDialog.h LoginControl.h EditClientDialog.h Constants.h ManageMatchesView.h MatchTableModel.h MatchingAlgorithm.h KuhnMunkres.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Control.cpp Animal.cpp AnimalTableModel.cpp ManageAnimalsView.cpp AddAnimalDialog.cpp Store.cpp ClientTableModel.cpp Client.cpp DBHandler.cpp ManageClientsView.cpp Login.cpp CuacsAppView.cpp ClientManageStore.cpp BrowseAnimals.cpp Staff.cpp StaffCollection.cpp AddClientDialog.cpp SidebarClient.cpp SidebarStaff.cpp StaffManageStore.cpp Default.cpp DBQuery.cpp AnimalCollection.cpp ClientCollection.cpp StoreControl.cpp EditAnimalDialog.cpp LoginControl.cpp EditClientDialog.cpp ManageMatchesView.cpp MatchTableModel.cpp MatchingAlgorithm.cpp KuhnMunkres.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ManageAnimalsView.ui AddAnimalDialog.ui ManageClientsView.ui Login.ui CuacsAppView.ui ClientManageStore.ui BrowseAnimals.ui AddClientDialog.ui SidebarClient.ui SidebarStaff.ui StaffManageStore.ui Default.ui EditAnimalDialog.ui EditAnimalDialog.ui EditClientDialog.ui ManageMatchesView.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_stylesheet.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_stylesheet.cpp
qrc_stylesheet.cpp: stylesheet.qrc \
		/usr/lib/qt5/bin/rcc \
		images/cuacs_logo.png
	/usr/lib/qt5/bin/rcc -name stylesheet stylesheet.qrc -o qrc_stylesheet.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1y -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_AnimalTableModel.cpp moc_ManageAnimalsView.cpp moc_AddAnimalDialog.cpp moc_Store.cpp moc_ClientTableModel.cpp moc_ManageClientsView.cpp moc_Login.cpp moc_CuacsAppView.cpp moc_ClientManageStore.cpp moc_BrowseAnimals.cpp moc_StaffCollection.cpp moc_AddClientDialog.cpp moc_SidebarClient.cpp moc_SidebarStaff.cpp moc_StaffManageStore.cpp moc_Default.cpp moc_EditAnimalDialog.cpp moc_EditClientDialog.cpp moc_ManageMatchesView.cpp moc_MatchTableModel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AnimalTableModel.cpp moc_ManageAnimalsView.cpp moc_AddAnimalDialog.cpp moc_Store.cpp moc_ClientTableModel.cpp moc_ManageClientsView.cpp moc_Login.cpp moc_CuacsAppView.cpp moc_ClientManageStore.cpp moc_BrowseAnimals.cpp moc_StaffCollection.cpp moc_AddClientDialog.cpp moc_SidebarClient.cpp moc_SidebarStaff.cpp moc_StaffManageStore.cpp moc_Default.cpp moc_EditAnimalDialog.cpp moc_EditClientDialog.cpp moc_ManageMatchesView.cpp moc_MatchTableModel.cpp
moc_AnimalTableModel.cpp: Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		AnimalTableModel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include AnimalTableModel.h -o moc_AnimalTableModel.cpp

moc_ManageAnimalsView.cpp: AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		AddAnimalDialog.h \
		Control.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ManageAnimalsView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ManageAnimalsView.h -o moc_ManageAnimalsView.cpp

moc_AddAnimalDialog.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		AddAnimalDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include AddAnimalDialog.h -o moc_AddAnimalDialog.cpp

moc_Store.cpp: Animal.h \
		Constants.h \
		DBHandler.h \
		AnimalTableModel.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		Store.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Store.h -o moc_Store.cpp

moc_ClientTableModel.cpp: Client.h \
		Constants.h \
		Animal.h \
		DBHandler.h \
		DBQuery.h \
		Staff.h \
		ClientTableModel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClientTableModel.h -o moc_ClientTableModel.cpp

moc_ManageClientsView.cpp: ClientTableModel.h \
		Client.h \
		Constants.h \
		Animal.h \
		DBHandler.h \
		DBQuery.h \
		Staff.h \
		Control.h \
		AnimalTableModel.h \
		Store.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ManageClientsView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ManageClientsView.h -o moc_ManageClientsView.cpp

moc_Login.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		Login.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Login.h -o moc_Login.cpp

moc_CuacsAppView.cpp: Login.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		CuacsAppView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include CuacsAppView.h -o moc_CuacsAppView.cpp

moc_ClientManageStore.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ClientManageStore.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClientManageStore.h -o moc_ClientManageStore.cpp

moc_BrowseAnimals.cpp: AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Control.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		BrowseAnimals.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include BrowseAnimals.h -o moc_BrowseAnimals.cpp

moc_StaffCollection.cpp: Staff.h \
		DBHandler.h \
		Animal.h \
		Constants.h \
		DBQuery.h \
		Client.h \
		StaffCollection.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include StaffCollection.h -o moc_StaffCollection.cpp

moc_AddClientDialog.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		AddClientDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include AddClientDialog.h -o moc_AddClientDialog.cpp

moc_SidebarClient.cpp: SidebarClient.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SidebarClient.h -o moc_SidebarClient.cpp

moc_SidebarStaff.cpp: SidebarStaff.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SidebarStaff.h -o moc_SidebarStaff.cpp

moc_StaffManageStore.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		StaffManageStore.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include StaffManageStore.h -o moc_StaffManageStore.cpp

moc_Default.cpp: Default.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Default.h -o moc_Default.cpp

moc_EditAnimalDialog.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		EditAnimalDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include EditAnimalDialog.h -o moc_EditAnimalDialog.cpp

moc_EditClientDialog.cpp: Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		EditClientDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include EditClientDialog.h -o moc_EditClientDialog.cpp

moc_ManageMatchesView.cpp: Animal.h \
		Constants.h \
		Client.h \
		MatchTableModel.h \
		Control.h \
		AnimalTableModel.h \
		DBHandler.h \
		DBQuery.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ManageMatchesView.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ManageMatchesView.h -o moc_ManageMatchesView.cpp

moc_MatchTableModel.cpp: Animal.h \
		Constants.h \
		Client.h \
		MatchTableModel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_git/viewMatch/COMP_3004 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MatchTableModel.h -o moc_MatchTableModel.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ManageAnimalsView.h ui_AddAnimalDialog.h ui_ManageClientsView.h ui_Login.h ui_CuacsAppView.h ui_ClientManageStore.h ui_BrowseAnimals.h ui_AddClientDialog.h ui_SidebarClient.h ui_SidebarStaff.h ui_StaffManageStore.h ui_Default.h ui_EditAnimalDialog.h ui_EditAnimalDialog.h ui_EditClientDialog.h ui_ManageMatchesView.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ManageAnimalsView.h ui_AddAnimalDialog.h ui_ManageClientsView.h ui_Login.h ui_CuacsAppView.h ui_ClientManageStore.h ui_BrowseAnimals.h ui_AddClientDialog.h ui_SidebarClient.h ui_SidebarStaff.h ui_StaffManageStore.h ui_Default.h ui_EditAnimalDialog.h ui_EditAnimalDialog.h ui_EditClientDialog.h ui_ManageMatchesView.h
ui_ManageAnimalsView.h: ManageAnimalsView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ManageAnimalsView.ui -o ui_ManageAnimalsView.h

ui_AddAnimalDialog.h: AddAnimalDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic AddAnimalDialog.ui -o ui_AddAnimalDialog.h

ui_ManageClientsView.h: ManageClientsView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ManageClientsView.ui -o ui_ManageClientsView.h

ui_Login.h: Login.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Login.ui -o ui_Login.h

ui_CuacsAppView.h: CuacsAppView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CuacsAppView.ui -o ui_CuacsAppView.h

ui_ClientManageStore.h: ClientManageStore.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ClientManageStore.ui -o ui_ClientManageStore.h

ui_BrowseAnimals.h: BrowseAnimals.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic BrowseAnimals.ui -o ui_BrowseAnimals.h

ui_AddClientDialog.h: AddClientDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic AddClientDialog.ui -o ui_AddClientDialog.h

ui_SidebarClient.h: SidebarClient.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic SidebarClient.ui -o ui_SidebarClient.h

ui_SidebarStaff.h: SidebarStaff.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic SidebarStaff.ui -o ui_SidebarStaff.h

ui_StaffManageStore.h: StaffManageStore.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic StaffManageStore.ui -o ui_StaffManageStore.h

ui_Default.h: Default.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Default.ui -o ui_Default.h

ui_EditAnimalDialog.h: EditAnimalDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic EditAnimalDialog.ui -o ui_EditAnimalDialog.h

ui_EditAnimalDialog.h: EditAnimalDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic EditAnimalDialog.ui -o ui_EditAnimalDialog.h

ui_EditClientDialog.h: EditClientDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic EditClientDialog.ui -o ui_EditClientDialog.h

ui_ManageMatchesView.h: ManageMatchesView.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ManageMatchesView.ui -o ui_ManageMatchesView.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Control.o: Control.cpp Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Control.o Control.cpp

Animal.o: Animal.cpp Animal.h \
		Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Animal.o Animal.cpp

AnimalTableModel.o: AnimalTableModel.cpp AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalTableModel.o AnimalTableModel.cpp

ManageAnimalsView.o: ManageAnimalsView.cpp ManageAnimalsView.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		AddAnimalDialog.h \
		Control.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddClientDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		EditAnimalDialog.h \
		ui_ManageAnimalsView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManageAnimalsView.o ManageAnimalsView.cpp

AddAnimalDialog.o: AddAnimalDialog.cpp AddAnimalDialog.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ui_AddAnimalDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddAnimalDialog.o AddAnimalDialog.cpp

Store.o: Store.cpp Store.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		AnimalTableModel.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Store.o Store.cpp

ClientTableModel.o: ClientTableModel.cpp ClientTableModel.h \
		Client.h \
		Constants.h \
		Animal.h \
		DBHandler.h \
		DBQuery.h \
		Staff.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientTableModel.o ClientTableModel.cpp

Client.o: Client.cpp Client.h \
		Constants.h \
		Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Client.o Client.cpp

DBHandler.o: DBHandler.cpp DBHandler.h \
		Animal.h \
		Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBHandler.o DBHandler.cpp

ManageClientsView.o: ManageClientsView.cpp ManageClientsView.h \
		ClientTableModel.h \
		Client.h \
		Constants.h \
		Animal.h \
		DBHandler.h \
		DBQuery.h \
		Staff.h \
		Control.h \
		AnimalTableModel.h \
		Store.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageAnimalsView.h \
		AddAnimalDialog.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		AddClientDialog.h \
		ui_ManageClientsView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManageClientsView.o ManageClientsView.cpp

Login.o: Login.cpp Login.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ui_Login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Login.o Login.cpp

CuacsAppView.o: CuacsAppView.cpp CuacsAppView.h \
		Login.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		StoreControl.h \
		LoginControl.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		ui_CuacsAppView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CuacsAppView.o CuacsAppView.cpp

ClientManageStore.o: ClientManageStore.cpp ClientManageStore.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		StoreControl.h \
		LoginControl.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		ui_ClientManageStore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientManageStore.o ClientManageStore.cpp

BrowseAnimals.o: BrowseAnimals.cpp BrowseAnimals.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Control.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ui_BrowseAnimals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BrowseAnimals.o BrowseAnimals.cpp

Staff.o: Staff.cpp Staff.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Staff.o Staff.cpp

StaffCollection.o: StaffCollection.cpp StaffCollection.h \
		Staff.h \
		DBHandler.h \
		Animal.h \
		Constants.h \
		DBQuery.h \
		Client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StaffCollection.o StaffCollection.cpp

AddClientDialog.o: AddClientDialog.cpp AddClientDialog.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ui_AddClientDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddClientDialog.o AddClientDialog.cpp

SidebarClient.o: SidebarClient.cpp SidebarClient.h \
		ui_SidebarClient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SidebarClient.o SidebarClient.cpp

SidebarStaff.o: SidebarStaff.cpp SidebarStaff.h \
		ui_SidebarStaff.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SidebarStaff.o SidebarStaff.cpp

StaffManageStore.o: StaffManageStore.cpp StaffManageStore.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		Default.h \
		StoreControl.h \
		LoginControl.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		ui_StaffManageStore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StaffManageStore.o StaffManageStore.cpp

Default.o: Default.cpp Default.h \
		ui_Default.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Default.o Default.cpp

DBQuery.o: DBQuery.cpp DBQuery.h \
		DBHandler.h \
		Animal.h \
		Constants.h \
		Client.h \
		Staff.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBQuery.o DBQuery.cpp

AnimalCollection.o: AnimalCollection.cpp AnimalCollection.h \
		Animal.h \
		Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimalCollection.o AnimalCollection.cpp

ClientCollection.o: ClientCollection.cpp ClientCollection.h \
		Client.h \
		Constants.h \
		Animal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClientCollection.o ClientCollection.cpp

StoreControl.o: StoreControl.cpp StoreControl.h \
		Store.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		AnimalTableModel.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StoreControl.o StoreControl.cpp

EditAnimalDialog.o: EditAnimalDialog.cpp EditAnimalDialog.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ui_EditAnimalDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditAnimalDialog.o EditAnimalDialog.cpp

LoginControl.o: LoginControl.cpp LoginControl.h \
		Store.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		AnimalTableModel.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginControl.o LoginControl.cpp

EditClientDialog.o: EditClientDialog.cpp EditClientDialog.h \
		Control.h \
		AnimalTableModel.h \
		Animal.h \
		Constants.h \
		DBHandler.h \
		DBQuery.h \
		Client.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		MatchTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		ManageMatchesView.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		StoreControl.h \
		LoginControl.h \
		ui_EditClientDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditClientDialog.o EditClientDialog.cpp

ManageMatchesView.o: ManageMatchesView.cpp ManageMatchesView.h \
		Animal.h \
		Constants.h \
		Client.h \
		MatchTableModel.h \
		Control.h \
		AnimalTableModel.h \
		DBHandler.h \
		DBQuery.h \
		Staff.h \
		Store.h \
		ClientTableModel.h \
		StaffCollection.h \
		ClientCollection.h \
		AnimalCollection.h \
		MatchingAlgorithm.h \
		KuhnMunkres.h \
		CuacsAppView.h \
		Login.h \
		StaffManageStore.h \
		ManageClientsView.h \
		AddAnimalDialog.h \
		AddClientDialog.h \
		ManageAnimalsView.h \
		EditAnimalDialog.h \
		SidebarStaff.h \
		Default.h \
		ClientManageStore.h \
		BrowseAnimals.h \
		SidebarClient.h \
		EditClientDialog.h \
		StoreControl.h \
		LoginControl.h \
		ui_ManageMatchesView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManageMatchesView.o ManageMatchesView.cpp

MatchTableModel.o: MatchTableModel.cpp MatchTableModel.h \
		Animal.h \
		Constants.h \
		Client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MatchTableModel.o MatchTableModel.cpp

MatchingAlgorithm.o: MatchingAlgorithm.cpp MatchingAlgorithm.h \
		Animal.h \
		Constants.h \
		Client.h \
		KuhnMunkres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MatchingAlgorithm.o MatchingAlgorithm.cpp

KuhnMunkres.o: KuhnMunkres.cpp KuhnMunkres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KuhnMunkres.o KuhnMunkres.cpp

qrc_stylesheet.o: qrc_stylesheet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_stylesheet.o qrc_stylesheet.cpp

moc_AnimalTableModel.o: moc_AnimalTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AnimalTableModel.o moc_AnimalTableModel.cpp

moc_ManageAnimalsView.o: moc_ManageAnimalsView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ManageAnimalsView.o moc_ManageAnimalsView.cpp

moc_AddAnimalDialog.o: moc_AddAnimalDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddAnimalDialog.o moc_AddAnimalDialog.cpp

moc_Store.o: moc_Store.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Store.o moc_Store.cpp

moc_ClientTableModel.o: moc_ClientTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClientTableModel.o moc_ClientTableModel.cpp

moc_ManageClientsView.o: moc_ManageClientsView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ManageClientsView.o moc_ManageClientsView.cpp

moc_Login.o: moc_Login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Login.o moc_Login.cpp

moc_CuacsAppView.o: moc_CuacsAppView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CuacsAppView.o moc_CuacsAppView.cpp

moc_ClientManageStore.o: moc_ClientManageStore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ClientManageStore.o moc_ClientManageStore.cpp

moc_BrowseAnimals.o: moc_BrowseAnimals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BrowseAnimals.o moc_BrowseAnimals.cpp

moc_StaffCollection.o: moc_StaffCollection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StaffCollection.o moc_StaffCollection.cpp

moc_AddClientDialog.o: moc_AddClientDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddClientDialog.o moc_AddClientDialog.cpp

moc_SidebarClient.o: moc_SidebarClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SidebarClient.o moc_SidebarClient.cpp

moc_SidebarStaff.o: moc_SidebarStaff.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SidebarStaff.o moc_SidebarStaff.cpp

moc_StaffManageStore.o: moc_StaffManageStore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StaffManageStore.o moc_StaffManageStore.cpp

moc_Default.o: moc_Default.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Default.o moc_Default.cpp

moc_EditAnimalDialog.o: moc_EditAnimalDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditAnimalDialog.o moc_EditAnimalDialog.cpp

moc_EditClientDialog.o: moc_EditClientDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditClientDialog.o moc_EditClientDialog.cpp

moc_ManageMatchesView.o: moc_ManageMatchesView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ManageMatchesView.o moc_ManageMatchesView.cpp

moc_MatchTableModel.o: moc_MatchTableModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MatchTableModel.o moc_MatchTableModel.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

